//Generated by Lightning Kite's Mirror plugin
//AUTOMATICALLY GENERATED AND WILL BE OVERRIDDEN IF THIS MESSAGE IS PRESENT
package com.lightningkite.mirror.info


import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass

@Suppress("RemoveExplicitTypeArguments", "UNCHECKED_CAST", "USELESS_CAST")
object ClassInfoClassInfo: ClassInfo<ClassInfo<*>> {

   override val kClass: KClass<ClassInfo<*>> = ClassInfo::class
   override val modifiers: List<ClassInfo.Modifier> = listOf(ClassInfo.Modifier.Interface, ClassInfo.Modifier.Abstract)

   override val implements: List<Type<*>> = listOf()

   override val packageName: String = "com.lightningkite.mirror.info"
   override val owner: KClass<*>? = null
   override val ownerName: String? = null

   override val name: String = "ClassInfo"
   override val annotations: List<AnnotationInfo> = listOf()
   override val enumValues: List<ClassInfo<*>>? = null

   object Fields {
       
   }

   override val fields:List<FieldInfo<ClassInfo<*>, *>> = listOf()

   override fun construct(map: Map<String, Any?>): ClassInfo<kotlin.Any> = throw NotImplementedError()

}