//Generated by Lightning Kite's Mirror plugin
//AUTOMATICALLY GENERATED AND WILL BE OVERRIDDEN IF THIS MESSAGE IS PRESENT
package com.lightningkite.mirror.archive


import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass

@Suppress("RemoveExplicitTypeArguments", "UNCHECKED_CAST", "USELESS_CAST")
object ConditionOnItemNeverClassInfo: ClassInfo<ConditionOnItem.Never<*>> {

   override val kClass: KClass<ConditionOnItem.Never<*>> = ConditionOnItem.Never::class
   override val modifiers: List<ClassInfo.Modifier> = listOf()

   override val implements: List<Type<*>> = listOf()

   override val packageName: String = "com.lightningkite.mirror.archive"
   override val owner: KClass<*>? = ConditionOnItem::class
   override val ownerName: String? = "ConditionOnItem"

   override val name: String = "Never"
   override val annotations: List<AnnotationInfo> = listOf()
   override val enumValues: List<ConditionOnItem.Never<*>>? = null

   object Fields {
       
   }

   override val fields:List<FieldInfo<ConditionOnItem.Never<*>, *>> = listOf()

   override fun construct(map: Map<String, Any?>): ConditionOnItem.Never<kotlin.Any> {
       //Gather variables
       
           //Handle the optionals
       
       //Finally do the call
       return ConditionOnItem.Never<kotlin.Any>(
           
       )
   }

}