//Generated by Lightning Kite's Mirror plugin
//AUTOMATICALLY GENERATED AND WILL BE OVERRIDDEN IF THIS MESSAGE IS PRESENT
package com.lightningkite.mirror.archive


import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass

@Suppress("RemoveExplicitTypeArguments", "UNCHECKED_CAST", "USELESS_CAST")
object ConditionOnItemClassInfo: ClassInfo<ConditionOnItem<*>> {

   override val kClass: KClass<ConditionOnItem<*>> = ConditionOnItem::class
   override val modifiers: List<ClassInfo.Modifier> = listOf(ClassInfo.Modifier.Sealed)

   override val implements: List<Type<*>> = listOf()

   override val packageName: String = "com.lightningkite.mirror.archive"
   override val owner: KClass<*>? = null
   override val ownerName: String? = null

   override val name: String = "ConditionOnItem"
   override val annotations: List<AnnotationInfo> = listOf()
   override val enumValues: List<ConditionOnItem<*>>? = null

   object Fields {
       
   }

   override val fields:List<FieldInfo<ConditionOnItem<*>, *>> = listOf()

   override fun construct(map: Map<String, Any?>): ConditionOnItem<kotlin.Any> = throw NotImplementedError()

}