//Generated by Lightning Kite's Mirror plugin
package com.lightningkite.lokalize


import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass

@Suppress("RemoveExplicitTypeArguments", "UNCHECKED_CAST", "USELESS_CAST")
object TimeStampClassInfo: ClassInfo<TimeStamp> {

   override val kClass: KClass<TimeStamp> = TimeStamp::class
   override val modifiers: List<ClassInfo.Modifier> = listOf()

   override val implements: List<Type<*>> = listOf()

   override val packageName: String = "com.lightningkite.lokalize"
   override val owner: KClass<*>? = null
   override val ownerName: String? = null

   override val name: String = "TimeStamp"
   override val annotations: List<AnnotationInfo> = listOf()
   override val enumValues: List<TimeStamp>? = null

   object Fields {
       val millisecondsSinceEpoch = SerializedFieldInfo<TimeStamp, kotlin.Long>(TimeStampClassInfo, "millisecondsSinceEpoch", Type<kotlin.Long>(kotlin.Long::class, listOf(), false), false, { it.millisecondsSinceEpoch as kotlin.Long}, listOf())
   }

   override val fields:List<SerializedFieldInfo<TimeStamp, *>> = listOf(Fields.millisecondsSinceEpoch)

   override fun construct(map: Map<String, Any?>): TimeStamp {
       //Gather variables
       val millisecondsSinceEpoch:kotlin.Long = map["millisecondsSinceEpoch"] as kotlin.Long
           //Handle the optionals
       
       //Finally do the call
       return TimeStamp(
           millisecondsSinceEpoch = millisecondsSinceEpoch
       )
   }

}