//Generated by Lightning Kite's Mirror plugin
package com.lightningkite.rekwest.server

import com.lightningkite.kommon.exception.ExceptionNames
import com.lightningkite.lokalize.TimeStamp
import com.lightningkite.mirror.archive.*
import com.lightningkite.mirror.info.Indexed
import com.lightningkite.mirror.info.Mutates
import com.lightningkite.mirror.info.ThrowsTypes
import com.lightningkite.rekwest.ServerFunction
import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass

@Suppress("RemoveExplicitTypeArguments", "UNCHECKED_CAST", "USELESS_CAST")
object UserUpdateClassInfo: ClassInfo<User.Update> {

   override val kClass: KClass<User.Update> = User.Update::class
   override val modifiers: List<ClassInfo.Modifier> = listOf()

   override val implements: List<Type<*>> = listOf(Type<ServerFunction<User>>(ServerFunction::class, listOf(TypeProjection(Type<User>(User::class, listOf(), false), TypeProjection.Variance.INVARIANT)), false))

   override val packageName: String = "com.lightningkite.rekwest.server"
   override val owner: KClass<*>? = User::class
   override val ownerName: String? = "User"

   override val name: String = "Update"
   override val annotations: List<AnnotationInfo> = listOf(AnnotationInfo("Mutates", listOf()), AnnotationInfo("ThrowsTypes", listOf(ExceptionNames.ForbiddenException, ExceptionNames.NoSuchElementException)))
   override val enumValues: List<User.Update>? = null

   object Fields {
       val value = FieldInfo<User.Update, User>(UserUpdateClassInfo, "value", Type<User>(User::class, listOf(), false), false, { it.value as User}, listOf())
   }

   override val fields:List<FieldInfo<User.Update, *>> = listOf(Fields.value)

   override fun construct(map: Map<String, Any?>): User.Update {
       //Gather variables
       val value:User = map["value"] as User
           //Handle the optionals
       
       //Finally do the call
       return User.Update(
           value = value
       )
   }

}