//Generated by Lightning Kite's Mirror plugin
//AUTOMATICALLY GENERATED AND WILL BE OVERRIDDEN IF THIS MESSAGE IS PRESENT
package com.lightningkite.rekwest.server

import com.lightningkite.kommon.exception.ExceptionNames
import com.lightningkite.lokalize.TimeStamp
import com.lightningkite.mirror.info.Indexed
import com.lightningkite.mirror.info.Mutates
import com.lightningkite.mirror.info.ThrowsTypes
import com.lightningkite.rekwest.ServerFunction
import com.lightningkite.mirror.archive.*
import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass

@Suppress("RemoveExplicitTypeArguments", "UNCHECKED_CAST", "USELESS_CAST")
object UserDeleteClassInfo: ClassInfo<User.Delete> {

   override val kClass: KClass<User.Delete> = User.Delete::class
   override val modifiers: List<ClassInfo.Modifier> = listOf()

   override val implements: List<Type<*>> = listOf(Type<ServerFunction<Unit>>(ServerFunction::class, listOf(TypeProjection(Type<Unit>(Unit::class, listOf(), false), TypeProjection.Variance.INVARIANT)), false))

   override val packageName: String = "com.lightningkite.rekwest.server"
   override val owner: KClass<*>? = User::class
   override val ownerName: String? = "User"

   override val name: String = "Delete"
   override val annotations: List<AnnotationInfo> = listOf(AnnotationInfo("@Mutates", listOf()), AnnotationInfo("@ThrowsTypes", listOf(ExceptionNames.ForbiddenException, ExceptionNames.NoSuchElementException)))
   override val enumValues: List<User.Delete>? = null

   object Fields {
       val id = FieldInfo<User.Delete, Reference<User>>(UserDeleteClassInfo, "id", Type<Reference<User>>(Reference::class, listOf(TypeProjection(Type<User>(User::class, listOf(), false), TypeProjection.Variance.INVARIANT)), false), false, { it.id as Reference<User>}, listOf())
   }

   override val fields:List<FieldInfo<User.Delete, *>> = listOf(Fields.id)

   override fun construct(map: Map<String, Any?>): User.Delete {
       //Gather variables
       val id:Reference<User> = map["id"] as Reference<User>
           //Handle the optionals
       
       //Finally do the call
       return User.Delete(
           id = id
       )
   }

}